#!/bin/bash

/usr/bin/asciidoctor \
    -r asciidoctor-html5s \
    -b html5s \
    -r asciidoctor-diagram \
    --attribute nofooter \
    --attribute docinfo=shared \
    --attribute icons=font \
    --attribute source-highlighter=highlightjs \
    --attribute sectlinks \
    --attribute sectanchors \
    --attribute figure-caption! \
    --attribute toc-title! \
    "$@"