---
title: "Les BT et nos joueurs"
summary: "Les BT et nos joueurs"
date: 2022-07-09T00:00:01
tags:
    - "aos"
    - "bt"
---

Les BattleTome représentés à l'association :


== Grand Alliance Order

[.les_codex]
[%header,format=csv,separator=";",cols="3,5,1"]
|====
BattleTome ;Version ;Dispo à l'asso
Cities of Sigmar; v3; icon:check[]
Daughters of Khaine; v3; icon:ban[]
Fyreslayers; v3; icon:check[]
Idoneth Deepkin; v3; icon:ban[]
Kharadron Overlords; v3; icon:ban[]
Lumineth Realm-lords; v3; icon:ban[]
Seraphon; v2; icon:check[]
Stormcast Eternals; v3; icon:check[]
Sylvaneth; v3; icon:check[]
|====


== Grand Alliance Chaos

[.les_codex]
[%header,format=csv,separator=";",cols="3,5,1"]
|====
BattleTome ;Version ;Dispo à l'asso
Beasts of Chaos; v3; icon:check[]
Blades of Khorne; v3; icon:check[]
Disciples of Tzeentch; v3; icon:check[]
Hedonites of Slaanesh; v3; icon:ban[]
Maggotkin of Nurgle; v3; icon:check[]
Skaven; v3; icon:check[]
Slaves to Darkness; v3; icon:check[]
|====


== Grand Alliance Death

[.les_codex]
[%header,format=csv,separator=";",cols="3,5,1"]
|====
BattleTome ;Version ;Dispo à l'asso
Flesh-eater Courts; v3; icon:check[]
Soulblight; v3; icon:check[]
Nighthaunt; v3; icon:check[]
Ossiarch Bonereapers; v3; icon:check[]
|====


== Grand Alliance Destruction

[.les_codex]
[%header,format=csv,separator=";",cols="3,5,1"]
|====
BattleTome ;Version ;Dispo à l'asso
Gloomspite Gitz; v3; icon:check[]
Ogor Mawtribes; v3; icon:check[]
Orruk Warclans; v3; icon:check[]
Sons of Behemat; v3; icon:check[]
|====
